#!/bin/bash

echo "🚀 Universal Feign Gateway Demo"
echo "================================"
echo ""

echo "This demo shows how a single API gateway endpoint handles ALL requests dynamically:"
echo ""

echo "📋 Available Endpoints (ALL handled by single universal client):"
echo "  GET    /api/users              - Get all users"
echo "  GET    /api/users/{id}         - Get user by ID"
echo "  POST   /api/users              - Create user"
echo "  PUT    /api/users/{id}         - Update user"
echo "  DELETE /api/users/{id}         - Delete user"
echo ""
echo "  GET    /api/orders             - Get all orders"
echo "  GET    /api/orders/{id}        - Get order by ID"
echo "  GET    /api/orders/user/{id}   - Get orders by user"
echo "  POST   /api/orders             - Create order"
echo ""
echo "  GET    /api/products           - Get all products"
echo "  GET    /api/products/{id}      - Get product by ID"
echo "  GET    /api/products/category/{category} - Get products by category"
echo "  POST   /api/products           - Create product"
echo ""
echo "  GET    /api/payments           - Get all payments"
echo "  GET    /api/payments/{id}      - Get payment by ID"
echo "  GET    /api/payments/order/{id} - Get payments by order"
echo "  POST   /api/payments           - Create payment"
echo ""
echo "  GET    /api/notifications      - Get all notifications"
echo "  GET    /api/notifications/{id} - Get notification by ID"
echo "  GET    /api/notifications/user/{id} - Get notifications by user"
echo "  POST   /api/notifications      - Create notification"
echo ""
echo "  GET    /api/health             - Health check"
echo ""

echo "🔧 How it works:"
echo "1. Single endpoint: /api/** catches ALL requests"
echo "2. Dynamic service detection: /users -> user-service, /payments -> payment-service, etc."
echo "3. Whitelist validation: Checks if service/path is allowed"
echo "4. Universal Feign client: ONE client handles ALL services dynamically"
echo "5. Response: Returns consistent ApiResponse format"
echo ""

echo "🎯 Key Features:"
echo "✅ Universal endpoint - one controller handles everything"
echo "✅ Universal Feign client - one client for all services"
echo "✅ Dynamic service routing - no hardcoded service mappings"
echo "✅ Whitelist security configuration"
echo "✅ Automatic service discovery from path patterns"
echo "✅ Consistent error handling and response format"
echo "✅ Easy to add new services - just update whitelist!"
echo ""

echo "💡 Adding New Services:"
echo "Just add to application.yml whitelist:"
echo "  - name: inventory-service"
echo "    base-url: http://localhost:8084"
echo "    endpoints:"
echo "      - /inventories/**"
echo "Then use: GET /api/inventories (automatically works!)"
echo ""

echo "To test the gateway, run:"
echo "  ./run.sh     # Start the application"
echo "  ./test-api.sh # Test all endpoints"
echo ""
