server:
  port: 8080

spring:
  application:
    name: feign-gateway
  cloud:
    loadbalancer:
      enabled: true

# Feign client configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

# Performance and scalability configuration
gateway:
  performance:
    # Connection pool settings
    connection-pool:
      max-total: 500
      max-per-route: 100
      validate-after-inactivity: 2000
      keep-alive-time: 30
    
    # Thread pool settings
    thread-pool:
      core-size: 20
      max-size: 100
      queue-capacity: 500
      keep-alive-seconds: 60
    
    # Caching settings
    cache:
      enabled: true
      ttl: 300 # 5 minutes
      max-size: 1000
    
    # Circuit breaker settings
    circuit-breaker:
      enabled: true
      failure-threshold: 5
      timeout-duration: 60000
      success-threshold: 3
    
    # Rate limiting settings
    rate-limiting:
      enabled: false # Will be enabled with Redis
      requests-per-minute: 1000
      burst-capacity: 100
    
    # Monitoring settings
    monitoring:
      enabled: true
      metrics-retention: 3600 # 1 hour
      health-check-interval: 30

# Whitelist configuration for allowed services
gateway:
  whitelist:
    enabled: true
    services:
      - name: user-service
        base-url: https://jsonplaceholder.typicode.com
        endpoints:
          - /users/**
          - /users/{id}
      - name: post-service
        base-url: https://dummyjson.com
        endpoints:
          - /posts/**
          - /posts/{id}
      - name: comment-service
        base-url: https://dummyjson.com
        endpoints:
          - /comments/**
          - /comments/{id}

# Logging configuration
logging:
  level:
    com.example.feigngateway: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    showExtensions: true
    showCommonExtensions: true
  show-actuator: true
  group-configs:
    - group: 'gateway'
      display-name: 'Gateway API'
      paths-to-match: '/api/execution/**'
